# Generated by Django 5.1.5 on 2025-02-14 13:21

import api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_dob', models.DateField()),
                ('stud_gender', models.CharField(max_length=10)),
                ('stud_location', models.CharField(max_length=50)),
                ('stud_contact', models.BigIntegerField(unique=True)),
                ('stud_parentscontact', models.BigIntegerField(unique=True)),
                ('stud_email', models.CharField(max_length=50, unique=True)),
                ('stud_branch', models.CharField(max_length=20)),
                ('stud_yoa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('total_fees', models.IntegerField()),
                ('fees_paid', models.IntegerField()),
                ('paid_date', models.DateField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2025, 2, 14, 18, 50, 59, 991851))),
                ('compitation_name', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
    ]
