# Generated by Django 5.1.5 on 2025-03-25 16:56

import api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_dob', models.DateField()),
                ('stud_gender', models.CharField(max_length=10)),
                ('stud_location', models.CharField(max_length=50)),
                ('stud_contact', models.BigIntegerField(unique=True)),
                ('stud_parentscontact', models.BigIntegerField(unique=True)),
                ('stud_email', models.CharField(max_length=50, unique=True)),
                ('stud_branch', models.CharField(max_length=20)),
                ('stud_yoa', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('total_fees', models.IntegerField()),
                ('fees_paid', models.IntegerField()),
                ('paid_date', models.DateField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CIE_Stud_Written',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('sem', models.IntegerField()),
                ('subject_name_1', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_2', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_3', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_4', models.CharField(blank=True, default=None, max_length=100)),
                ('marks_1', models.IntegerField(blank=True, default=None, null=True)),
                ('marks_2', models.IntegerField(blank=True, default=None, null=True)),
                ('marks_3', models.IntegerField(blank=True, default=None, null=True)),
                ('marks_4', models.IntegerField(blank=True, default=None, null=True)),
                ('cie_no', models.IntegerField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
        migrations.CreateModel(
            name='CIE_Stud_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('sem', models.IntegerField()),
                ('subject_name_1', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_2', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_3', models.CharField(blank=True, default=None, max_length=100)),
                ('subject_name_4', models.CharField(blank=True, default=None, max_length=100)),
                ('marks_1', models.IntegerField(blank=True, null=True)),
                ('marks_2', models.IntegerField(blank=True, null=True)),
                ('marks_3', models.IntegerField(blank=True, null=True)),
                ('marks_4', models.IntegerField(blank=True, null=True)),
                ('cie_no', models.IntegerField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
        migrations.CreateModel(
            name='CIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('no_cie', models.IntegerField()),
                ('attended', models.IntegerField()),
                ('written', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.BigIntegerField(blank=True, default=api.models.create_new_ref_number, editable=False, unique=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2025, 3, 25, 22, 26, 33, 444433))),
                ('compitation_name', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stud')),
            ],
        ),
    ]
